### ISSUE TITLE
How to obtain corrected expression matrices?

### ISSUE THREAD

**Issue by 23jinny** [KChen-lab/cyclum#6]
Hi,
Seurat cell cycle correction doesn't seem to work very well and I would love to use Cyclum to obtain the cell cycle corrected gene expression matrix (as mentioned in the documents and paper) but I can't seem to find any related documentation/code, all the demos/documentation only show how to obtain pseudotime. I would really appreciate some help.
Thanks in advance!

**Comment by lshh125** [comment]
Hello,

Sorry for the late reply and thank you for bringing this to our attention. Indeed, this functionality was originally in our postprocessing in R and was missing in the Python pipeline. 

We have just added it into the Python package as `model.get_circular_component(pseudotime)`. An example on the mESC dataset is shown in https://github.com/KChen-lab/Cyclum/blob/master/tests/notebooks/mESC-with-regress-out.ipynb. Hope this solves the issue.

Best,
Shaoheng
