### ISSUE TITLE
How to manually set k linear components

### ISSUE THREAD

**Issue by e1992** [KChen-lab/cyclum#7]
Hi! Thanks for making cycle available, its very useful! I've been using it to find psuedotime for a data set where I know the cell cycle phases (early G1, late G1, S and G2/M in my case). I used the auto tuning which selects 1 linear component for the model. Using this the result looks pretty good, but my S and G2/M phase cells aren't fully separated. I would like to try increasing the linear components to compare, how can I do this? Is there a way to create model for a set number of components? 
or would you suggest changing other parameters? 
Thanks for your help!

**Comment by lshh125** [comment]
Sorry for the late reply. You certainly can! You can refer to block 6 in this example: https://github.com/KChen-lab/Cyclum/blob/master/tests/notebooks/McDavid-PC3.ipynb

Where the "n_linear_bypass" is what you would want to use for that purpose. Good luck.

**Comment by lshh125** [comment]
I'll close the question now. If you have additional questions few free to reopen. Thanks!
